### ISSUE TITLE
iscsictl login Input/output error

### ISSUE THREAD

**Issue by lokiki** [iscsi-osx/iSCSIInitiator#19]
Hi,

First thank you for your initiative of developing and iscsi initiator for OS X.
I've been able to successfully use the software to mount multiple LUN with a IETD server.

After a few tests, it appears that I'm getting an Input/output error after manipulating more than 1 LUN.

```shell
# iscsictl list targets
iqn.2001-04.com.example:storage.disk2.sys1.xyz <inactive, static>
	10.51.1.98 <inactive, port 3260, interface default>
iqn.2015-01.net.42:b71d51f06599e6df976ea78d081ab711 <inactive, static>
	10.51.1.99 <inactive, port 3260, interface default>
# iscsictl login iqn.2001-04.com.example:storage.disk2.sys1.xyz
iscsictl: Input/output error
# iscsictl login iqn.2015-01.net.42:b71d51f06599e6df976ea78d081ab711
iscsictl: Input/output error
```

In my /var/log/system.log I also get 
```shell
Dec  9 17:17:02 dump-accueil-1 iscsid[82]: Login to <iqn.2015-01.net.42:b71d51f06599e6df976ea78d081ab711,10.51.1.99:3260 interface default> failed: Input/output error
```

I do not see any traffic coming up on my server network interface.

If I remove completely the software/wipe the Mac and try to reinstall I can often get the following behavior:

```shell
# iscsictl add [...]
# iscscitl login [...]
```

login won't print anything and won't send any TCP packets to the server.
mount won't work too.

It's strange since it's been working at first.

The tests have been done on Mac OS X 10.10.5

**Comment by nsinenian** [comment]
You mentioned that you were able to successfully mount multiple LUNs.  Does the problem disappear when you reboot, and return after some time?  (e.g., after a reboot, does the first login work ok?)

An IO error in this case means that `iscsictl` cannot communicate with the daemon - either because it is not running, or something causes the daemon to crash (a potential bug or something else), or the daemon is hanging on trying to process the previous request.

If this occurs again, please provide the CPU usage of `iscsid` in the activity monitor. If you have found a series of steps (`iscsictl` commands) that can reproduce this issue every time please let me know and I will debug the scenario.

**Comment by nsinenian** [comment]
Please let me know if you still experience these issues with the new beta release (with installer).

**Comment by ryansyah** [comment]
Well, Hello.

I seem to have run into this bug this evening while trying to add a 2nd target.
Running the following commands from a macOS 10.12.2 host:
```
$ iscsictl list targets
iqn.2003-12.org.morphium:photos <inactive, static>
$ iscsictl list luns
iqn.2003-12.org.morphium:pictures <scsi domain 0, target 0>
	FREEBSD CTLDISK 0001
	Serial Number MYSERIAL   0
	lun 0: type 0x00 (Block device)
		disk2: 1.1 TB (2147483648 512 byte blocks)
$ iscsictl login iqn.2003-12.org.morphium:photos,192.168.23.13


from `/var/log/system.log`:
```
Dec 16 22:40:36 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid[99]): Service exited with abnormal code: 35
Dec 16 22:40:36 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid): Service only ran for 1 seconds. Pushing respawn out by 9 seconds.
Dec 16 22:40:49 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid[468]): Service exited due to signal: Segmentation fault: 11 sent by exc handler[0]
Dec 16 22:40:49 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Dec 16 22:40:59 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid[637]): Service exited due to signal: Segmentation fault: 11 sent by exc handler[0]
Dec 16 22:40:59 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Dec 16 22:41:09 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid[655]): Service exited due to signal: Segmentation fault: 11 sent by exc handler[0]
Dec 16 22:41:09 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Dec 16 22:41:19 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid[672]): Service exited due to signal: Segmentation fault: 11 sent by exc handler[0]
Dec 16 22:41:19 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Dec 16 22:41:29 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid[675]): Service exited due to signal: Segmentation fault: 11 sent by exc handler[0]
Dec 16 22:41:29 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Dec 16 22:41:39 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid[678]): Service exited due to signal: Segmentation fault: 11 sent by exc handler[0]
Dec 16 22:41:39 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Dec 16 22:41:49 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid[689]): Service exited due to signal: Segmentation fault: 11 sent by exc handler[0]
Dec 16 22:41:49 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Dec 16 22:41:59 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid[708]): Service exited due to signal: Segmentation fault: 11 sent by exc handler[0]
Dec 16 22:41:59 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Dec 16 22:42:09 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid[710]): Service exited due to signal: Segmentation fault: 11 sent by exc handler[0]
Dec 16 22:42:09 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Dec 16 22:42:19 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid[713]): Service exited due to signal: Segmentation fault: 11 sent by exc handler[0]
Dec 16 22:42:19 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Dec 16 22:42:29 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid[719]): Service exited due to signal: Segmentation fault: 11 sent by exc handler[0]
Dec 16 22:42:29 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Dec 16 22:42:39 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid[722]): Service exited due to signal: Segmentation fault: 11 sent by exc handler[0]
Dec 16 22:42:39 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Dec 16 22:42:49 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid[724]): Service exited due to signal: Segmentation fault: 11 sent by exc handler[0]
Dec 16 22:42:49 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Dec 16 22:42:59 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid[745]): Service exited due to signal: Segmentation fault: 11 sent by exc handler[0]
Dec 16 22:42:59 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Dec 16 22:43:10 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid[746]): Service exited due to signal: Segmentation fault: 11 sent by exc handler[0]
Dec 16 22:43:10 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Dec 16 22:43:20 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid[749]): Service exited due to signal: Segmentation fault: 11 sent by exc handler[0]
Dec 16 22:43:20 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Dec 16 22:43:30 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid[750]): Service exited due to signal: Segmentation fault: 11 sent by exc handler[0]
Dec 16 22:43:30 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Dec 16 22:43:40 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid[752]): Service exited due to signal: Segmentation fault: 11 sent by exc handler[0]
Dec 16 22:43:40 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Dec 16 22:43:50 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid[753]): Service exited due to signal: Segmentation fault: 11 sent by exc handler[0]
Dec 16 22:43:50 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Dec 16 22:44:00 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid[759]): Service exited due to signal: Segmentation fault: 11 sent by exc handler[0]
Dec 16 22:44:00 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Dec 16 22:44:10 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid[781]): Service exited due to signal: Segmentation fault: 11 sent by exc handler[0]
Dec 16 22:44:10 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Dec 16 22:44:20 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid[785]): Service exited due to signal: Segmentation fault: 11 sent by exc handler[0]
Dec 16 22:44:20 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Dec 16 22:44:30 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid[788]): Service exited due to signal: Segmentation fault: 11 sent by exc handler[0]
Dec 16 22:44:30 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Dec 16 22:44:40 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid[795]): Service exited due to signal: Segmentation fault: 11 sent by exc handler[0]
Dec 16 22:44:40 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Dec 16 22:44:50 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid[800]): Service exited due to signal: Segmentation fault: 11 sent by exc handler[0]
Dec 16 22:44:50 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Dec 16 22:45:00 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid[815]): Service exited due to signal: Segmentation fault: 11 sent by exc handler[0]
Dec 16 22:45:00 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Dec 16 22:45:10 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid[820]): Service exited due to signal: Segmentation fault: 11 sent by exc handler[0]
Dec 16 22:45:10 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Dec 16 22:45:20 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid[826]): Service exited due to signal: Segmentation fault: 11 sent by exc handler[0]
Dec 16 22:45:20 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Dec 16 22:45:30 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid[827]): Service exited due to signal: Segmentation fault: 11 sent by exc handler[0]
Dec 16 22:45:30 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Dec 16 22:45:40 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid[832]): Service exited due to signal: Segmentation fault: 11 sent by exc handler[0]
Dec 16 22:45:40 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Dec 16 22:45:50 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid[838]): Service exited due to signal: Segmentation fault: 11 sent by exc handler[0]
Dec 16 22:45:50 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Dec 16 22:46:00 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid[841]): Service exited due to signal: Segmentation fault: 11 sent by exc handler[0]
Dec 16 22:46:00 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Dec 16 22:46:10 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid[855]): Service exited due to signal: Segmentation fault: 11 sent by exc handler[0]
Dec 16 22:46:10 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Dec 16 22:46:20 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid[857]): Service exited due to signal: Segmentation fault: 11 sent by exc handler[0]
Dec 16 22:46:20 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Dec 16 22:46:31 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid[858]): Service exited due to signal: Segmentation fault: 11 sent by exc handler[0]
Dec 16 22:46:31 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Dec 16 22:46:41 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid[860]): Service exited due to signal: Segmentation fault: 11 sent by exc handler[0]
Dec 16 22:46:41 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Dec 16 22:46:51 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid[861]): Service exited due to signal: Segmentation fault: 11 sent by exc handler[0]
Dec 16 22:46:51 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Dec 16 22:47:01 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid[864]): Service exited due to signal: Segmentation fault: 11 sent by exc handler[0]
Dec 16 22:47:01 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Dec 16 22:47:11 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid[865]): Service exited due to signal: Segmentation fault: 11 sent by exc handler[0]
Dec 16 22:47:11 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Dec 16 22:47:21 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid[867]): Service exited due to signal: Segmentation fault: 11 sent by exc handler[0]
Dec 16 22:47:21 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Dec 16 22:47:31 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid[868]): Service exited due to signal: Segmentation fault: 11 sent by exc handler[0]
Dec 16 22:47:31 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Dec 16 22:47:41 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid[871]): Service exited due to signal: Segmentation fault: 11 sent by exc handler[0]
Dec 16 22:47:41 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Dec 16 22:47:51 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid[874]): Service exited due to signal: Segmentation fault: 11 sent by exc handler[0]
Dec 16 22:47:51 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Dec 16 22:48:01 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid[876]): Service exited due to signal: Segmentation fault: 11 sent by exc handler[0]
Dec 16 22:48:01 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Dec 16 22:48:11 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid[878]): Service exited due to signal: Segmentation fault: 11 sent by exc handler[0]
Dec 16 22:48:11 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Dec 16 22:48:21 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid[880]): Service exited due to signal: Segmentation fault: 11 sent by exc handler[0]
Dec 16 22:48:21 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Dec 16 22:48:31 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid[882]): Service exited due to signal: Segmentation fault: 11 sent by exc handler[0]
Dec 16 22:48:31 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Dec 16 22:48:41 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid[885]): Service exited due to signal: Segmentation fault: 11 sent by exc handler[0]
Dec 16 22:48:41 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Dec 16 22:48:51 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid[889]): Service exited due to signal: Trace/BPT trap: 5 sent by exc handler[0]
Dec 16 22:48:51 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Dec 16 22:49:01 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid[893]): Service exited due to signal: Segmentation fault: 11 sent by exc handler[0]
Dec 16 22:49:01 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Dec 16 22:49:11 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid[896]): Service exited due to signal: Segmentation fault: 11 sent by exc handler[0]
Dec 16 22:49:11 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Dec 16 22:49:21 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid[899]): Service exited due to signal: Segmentation fault: 11 sent by exc handler[0]
Dec 16 22:49:21 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Dec 16 22:49:31 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid[902]): Service exited due to signal: Segmentation fault: 11 sent by exc handler[0]
Dec 16 22:49:31 mini com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
```
