### ISSUE TITLE
Invalid IQN and (was) cant load Kext

### ISSUE THREAD

**Issue by sparkrevolutions** [iscsi-osx/iSCSIInitiator#34]
Hi,

I commented on a previously closed issue (https://github.com/iscsi-osx/iSCSIInitiator/issues/16).

Same problem as this person had. Running Mavericks. I have ran terminal command in readme to load unsigned kexts but no luck. Kext remains unloaded and receive same error message.

Any ideas?

**Comment by sparkrevolutions** [comment]
Upon further research, the dev arguments were only added in Yosemite (https://forums.developer.apple.com/thread/9332). Going to try using Kext Utility to install. Will post result

**Comment by sparkrevolutions** [comment]
After running Kext Utility, I was able to drag the kext into the Kext Utility App and then use the kextload command "sudo kextload /System/Library/Extensions/iSCSIInitiator.kext" to successfully load the kext. Perhaps worth adding to the readme?

**Comment by sparkrevolutions** [comment]
Now I have a different issue. It wont accept my target name. Trying to follow the Wiki on initiator configuration. Both this and trying to add a target result in:
The specified target name is not a valid IQN or EUI-64 identifier

Using the following commands:
sudo iscsictl modify initiator-config -node-name iqn.1997-05.tw.com.proware:proips-006926bc0:dev0:ctr1

and

sudo iscsictl add target iqn.1997-05.tw.com.proware:proips-006926bc0:dev0.ctr1,192.1.20.30

**Comment by sparkrevolutions** [comment]
Can anybody help me please?

**Comment by nsinenian** [comment]
The invalid IQN issue was opened and closed some time ago; please see those comments. The IQN validation code only allowed for 3-character TLDs, and you have a 2 character TLD (i.e., .tw). This was addressed in the develop branch and has yet to make it into master (and hence the next beta release), so it shouldn't be a problem moving forward. Please use the develop branch until this has been resolved. If the problem persists using the develop branch, please let us know.

As for the second issue, the security restrictions dictate different requirements for OS El Capitan (i.e., the extension is installed in /Library/Extensions instead of /System/Library/Extensions. The best solution is to adapt the installation script accordingly for OS X, I will make the necessary changes for the next commit.

**Comment by nsinenian** [comment]
I'm closing this as the necessary changes have been made (develop branch). The next beta release will absorb these changes.
