### ISSUE TITLE
kernel_task

### ISSUE THREAD

**Issue by heapxor** [iscsi-osx/iSCSIInitiator#40]
Hi,
isnt the code buggy? I setup the initiator on the el capitan, when i transfer around 3GB of data to the mounted location the kernel_task starts to use 80% cpu and machine is simply non-responsive until i reboot it.

any idea?

**Comment by heapxor** [comment]
Ok, i think this application has serious issue, with memory handling or i dont know... I installed globalsans and tried the same scenario. All works fine, no high cpu usage, no 100% of ram consumption, no SWAP used. I transferred with both apps 5GB file, globalsans 100% file transferred all works good, iscsiinitiator - pc died after around 3GB of data was transferred, out of cpu/ram/swap.

**Comment by nsinenian** [comment]
A few things:

1. It's a beta release, so expect bugs.

2. The memory leak you're referring to has already been fixed, but the
binaries are older.  This is obvious from the date stamp on the binary vs
the develop branch.

3. If you're going to bother installing a beta, please leave constructive
feedback so that we can improve things (simply saying that x works and that
ours has issues doesn't help anyone). The whole point of github is to build
something together. So if you do find an issue and have a diagnosis or a
fix please let us know.

**Comment by heapxor** [comment]
Hi there,
the test was done only to figure out where is the bug.

Ok, does it mean that dmg on the site has binaries that are old with bug? Could you please export new (the latest dmg) and i can double test?


Thanks!

**Comment by heapxor** [comment]
Hi,

I compiled the client from the sources and same issue occurred so looks like this bug was not fixed or its other bug ... could you please advice?
