### ISSUE TITLE
Possible Beta 4 performance degradation

### ISSUE THREAD

**Issue by yabba235** [iscsi-osx/iSCSIInitiator#62]
Hi ! 
I install latest beta but it has lower R/W speed 59/79MB/s ( AJA test ).
Beta 3 get 89/90MB/s in AJA test.
El Capitan 10.11.

**Comment by nsinenian** [comment]
Please use more descriptive names for issues, as it may help others also.

The changes made since beta-3 have to do with the daemon and the command line utility. Little to no changes have been made to the kernel that would affect performance, so I don't have an answer for you. 

Did you conduct the beta-3 test just now, or when beta-3 was released?

If you have not done so already, I'd suggest conducting both tests back-to-back (remove beta 4, install beta 3, re-run test, remove beta 3, install beta-4 and re-run test).

**Comment by yabba235** [comment]
Under macos sierra 10.12 GM write speed 80 to 59MB/s, read speed 90MB/s.
Test file size from 256 to 1GB - ( AJA Test ).

**Comment by yabba235** [comment]
Confirm speed degradation under macos sierra 10.12 (16A319).
R/W 98/73-58MB/s.
Beta 4 :) - perhaps slow write operation is only in beta os  but this build is  almost final.

**Comment by nsinenian** [comment]
I'm confused about which speeds you got with El Capitan vs Sierra and beta 3 vs beta 4. For example, your post 2 days ago was confusing - unclear whether it was beta 3 or 4. Please be clearer in order to help us. I'd suggest making a table:

|        | El Capitan (Read) | El Capitan (Write) | Sierra (Read) | Sierra (Write) |
|--------|-------------------|--------------------|---------------|----------------|
| Beta 3 |                   |                    |               |                |
| Beta 4 |                   |                    |               |                |


As for the errors like "iscsictl: Unknown error: -536870160", I need to know if it is reproducible (does it happen every time?), and how to reproduce it. Otherwise, while your comment is appreciated it is of little value to the debugging process.

Keep in mind that there may be changes in Sierra and compatibility has not been tested (not guaranteed at this point). You may get all kinds of errors.

**Comment by yabba235** [comment]
Sorry for my chaotic description, but i&#39;m only simply user :)  So, one again in order:   El Capitan (Read) El Capitan (Write) Sierra (Read)  Sierra (Write)  Beta 3              90               80             96              74   Beta 4              89               59             98              74        Errors Beta 4 from terminal   Last login: Mon Sep 12 18:35:37 on console  Mac-mini-tb:~ tomek$ /usr/local/bin/iscsictl login target iqn.2004-04.com.qnap:ts-453min  Attached iqn.2004-04.com.qnap:ts-453min &lt;scsi domain 0, target 0&gt;  QNAP iSCSI Storage 4.0  Serial Number e4d2f3c2-0cbb-48d4-8941-6fec2b  lun 0: type 0x00 (Block device)  Mac-mini-tb:~ tomek$ /usr/local/bin/iscsictl logout target iqn.2004-04.com.qnap:ts-453min  /usr/local/bin/iscsictl: Unknown error: -536870160   Errors Beta 3 from terminal (only from Sierra, on El Cap all is fine )   Last login: Mon Sep 12 18:54:33 on console  Restored session: pon 12 wrz 18:53:26 2016 CEST  Mac-mini-tb:~ tomek$ /usr/local/bin/iscsictl login target iqn.2004-04.com.qnap:ts-453min  Attached iqn.2004-04.com.qnap:ts-453min &lt;scsi domain 0, target 0&gt;  QNAP iSCSI Storage 4.0  Serial Number e4d2f3c2-0cbb-48d4-8941-6fec2b  lun 0: type 0x00 (Block device)  Mac-mini-tb:~ tomek$ /usr/local/bin/iscsictl logout target iqn.2004-04.com.qnap:ts-453min  /usr/local/bin/iscsictl: Operation not supported by device   BTW  Maybe some thinking about any GUI for this initiator - honestly I&#39;m not a big fan terminal :)    
                
              
               
                 
                  Dnia 12 września 2016 17:25 Nareg Sinenian &lt;notifications@github.com&gt; napisał(a):
                 
                 
                   I&#39;m confused about which speeds you got with El Capitan vs Sierra and beta 3 vs beta 4. For example, your post 2 days ago was confusing - unclear whether it was beta 3 or 4. Please be clearer in order to help us. I&#39;d suggest making a table: 

 
 
 
 
 El Capitan (Read) 
 El Capitan (Write) 
 Sierra (Read) 
 Sierra (Write) 
 
 
 
 
 Beta 3 
 
 
 
 
 
 
 Beta 4 
 
 
 
 
 
 
 

 As for the errors like &#34;iscsictl: Unknown error: -536870160&#34;, I need to know if it is reproducible (does it happen every time?), and how to reproduce it. Otherwise, while your comment is appreciated it is of little value to the debugging process. 

 Keep in mind that there may be changes in Sierra and compatibility has not been tested (not guaranteed at this point). You may get all kinds of errors.

**Comment by yabba235** [comment]
Lets talking about beta 5 :)
