### ISSUE TITLE
Permission denied.

### ISSUE THREAD

**Issue by chezpaul** [iscsi-osx/iSCSIInitiator#82]
Whatever I try, I get permission denied. I tried sudo command.
Running under MacOS Sierra 10.12.3

Pauls-iMac:~ paul$ iscsictl modify initiator-config -CHAP-chezpaul
iscsictl: Permission denied
Pauls-iMac:~ paul$ iscsictl modify initiator-config -authentication CHAP
iscsictl: Permission denied
Pauls-iMac:~ paul$ sudo iscsictl modify initiator-config -CHAP-chezpaul
Password:
iscsictl: Permission denied
Pauls-iMac:~ paul$ iscsictl list initiator-config
iqn.2015-01.com.localhost:initiator
	node-alias localhost
	Authentication: none
		CHAP-name localhost
		CHAP-secret <unspecified>
Pauls-iMac:~ paul$ iscsictl add discovery-portal 192.168.1.44
iscsictl: Permission denied

EDIT: I just realized on the first page talk about installation prerequisites.
Should I run this "csrutil disable" then in the recovery terminal window.
Will that fix my problem?
Should I uninstall first?

**Comment by nsinenian** [comment]
Uninstall first, then follow instructions for the prerequisites and install again.

**Comment by chezpaul** [comment]
Cool
Got it to work...
So how to you unmount the drive? Just unmount or do I need to logout?
And do I need to remove target before I add it from another mac (if I want to access from several different macs)
Thanks

**Comment by nsinenian** [comment]
Logout to unmount. Yes, you have to remove it before using it with another Mac (that's how iSCSI works). See wiki: https://github.com/iscsi-osx/iSCSIInitiator/wiki/Login-and-Disk-Access

If it unmounted by itself that's because there was a problem between the initiator/target. We've found issues with certain targets. In order to help me help you, I need the following information:

1. What kind of target or NAS are you using? 
2. Which version of the initiator (beta5?)
3. Use Wireshark to capture traffic from the moment you login until the drive automatically unmounts and post it for analysis.

Thanks.

**Comment by chezpaul** [comment]
The reason why it unmounted last night was because I put my NAS to sleep at midnight every night and totally forgot about that.  ;-)
Sorry.
I've had it logged in for the past hour and am bouncing left and right between iPhoto libraries and it seems to work fine. Great work man. Thanks for doing this.
I use a NAS QNAP TS-251 with he latest soft/firmware. 4.3
I was able to logout with a problem.
One more question... Do I need to unmount before logout?

**Comment by chezpaul** [comment]
One more question.
Can I turn csrutil back on once iSCSIInitiator is installed?

**Comment by nsinenian** [comment]
Nope. The kext isn't signed so you have to leave it disabled. The final (non-beta) release will have a signed kext.

**Comment by drviver** [comment]
but you can sign it manually with codesign -s user --force --deep path

**Comment by drviver** [comment]
but only valid for the mac it was signed on
